cryptoauth_blueprint.py
from cryptography.exceptions import InvalidSignature
from flask import Blueprint, flash, redirect, render_template, request, session, url_for, current_app as app

from util import random_base64, load_public_key, MalformedPublicKey, verify_spkac, verify_challenge

signature_login_poc = Blueprint('signature_login_poc', __name__, template_folder='templates')


@signature_login_poc.route('/register')
def register():
    challenge = random_base64(app.config['CHALLENGE_BYTES'])
    session['challenge_register'] = challenge

    return render_template('register.html', challenge=challenge)


@signature_login_poc.route('/register/submit', methods=['POST'])
def register_submit():
    public_key_pem = request.form.get('public_key')

    try:
        public_key = load_public_key(public_key_pem.encode('ascii'))
    except MalformedPublicKey as e:
        flash('malformed public key: {}'.format(e), 'danger')
        return redirect(url_for('main'))

    try:
        challenge = session.pop('challenge_register')
    except KeyError:
        flash('no challenge was stored in session', 'danger')
        return redirect(url_for('main'))

    try:
        verify_spkac(public_key, challenge, request.form.get('signature'))
    except InvalidSignature as e:
        flash('signature verification failed', 'danger')
        return redirect(url_for('main'))

    username = request.form.get('username')

    if len(username) == 0:
        flash('empty username not allowed', 'danger')
        return redirect(url_for('main'))

    if app.extensions['public_keys'].fetch_user_pem(username):
        flash('such user already exists', 'danger')
        return redirect(url_for('main'))

    app.extensions['public_keys'].store_user_pem(username, public_key_pem)

    flash('succesfully registered as {}'.format(username), 'success')
    return redirect(url_for('main'))


@signature_login_poc.route('/login')
def login():
    challenge = random_base64(app.config['CHALLENGE_BYTES'])
    session['challenge_login'] = challenge

    return render_template('login.html', challenge=challenge)


@signature_login_poc.route('/login/submit', methods=['POST'])
def login_submit():
    username = request.form.get('username')
    user_public_key_pem = app.extensions['public_keys'].fetch_user_pem(username)

    try:
        challenge = session.pop('challenge_login')
    except KeyError:
        flash('no challenge was stored in session', 'danger')
        return redirect(url_for('main'))

    if not user_public_key_pem:
        flash('no such user {}'.format(username), 'danger')
        return redirect(url_for('main'))

    user_public_key = load_public_key(user_public_key_pem)

    try:
        verify_challenge(user_public_key, challenge, request.form.get('signature'))
    except InvalidSignature:
        flash('you are not {}'.format(username), 'danger')
        return redirect(url_for('main'))

    flash('hello user {}'.format(username), 'success')
    return redirect(url_for('main'))

templates/_layout.html
<!DOCTYPE html>
<html>
<head>
    <title>Signature Login PoC</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
<div class="container extra-margin">
    <h1>Signature Login PoC</h1>
    {% block content %}{% endblock %}
</div>

<script src="{{ url_for('static', filename='util.js') }}"></script>
<script src="{{ url_for('static', filename='signing.js') }}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

templates/login.html
{% extends "_layout.html" %}

{% block content %}
    <h2>Login</h2>

    <form action="{{ url_for('.login_submit') }}" method="POST" id="login_form">
        <div class="form-group">
            <label>Challenge nonce (stored in session)</label>
            <textarea id="challenge" class="form-control monospace-font" rows="5" readonly>{{ challenge }}</textarea>
        </div>

        <div class="form-group">
            <label>Loaded public key</label>
            <textarea id="public_key" class="form-control monospace-font" rows="5" readonly></textarea>
        </div>

        <div class="form-group">
            <label>Signature of the challenge</label>
            <textarea id="signature" name="signature" class="form-control monospace-font" rows="5" readonly></textarea>
        </div>

        <div class="form-group">
            <label>User name</label>
            <input type="text" name="username" value="" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary">Log in</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='login.js') }}"></script>
{% endblock %}

templates/main.html
{% extends "_layout.html" %}

{% block content %}
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <a href="{{ url_for('signature_login_poc.login') }}" class="btn btn-default">login</a>
    <a href="{{ url_for('signature_login_poc.register') }}" class="btn btn-default">register</a>
{% endblock %}

templates/register.html
{% extends "_layout.html" %}

{% block content %}
    <h2>Register</h2>

    <form action="{{ url_for('.register_submit') }}" method="POST" id="register_form">
        <div class="form-group">
            <label>Challenge nonce (stored in session)</label>
            <textarea id="challenge" class="form-control monospace-font" rows="5" readonly>{{ challenge }}</textarea>
        </div>

        <div class="form-group">
            <label>Generated public key</label>
            <textarea id="public_key" name="public_key" class="form-control monospace-font" rows="5" readonly></textarea>
        </div>

        <div class="form-group">
            <label>Signature of the public key and challenge</label>
            <textarea id="signature" name="signature" class="form-control monospace-font" rows="5" readonly></textarea>
        </div>

        <div class="form-group">
            <label>User name</label>
            <input type="text" name="username" class="form-control" value="">
        </div>

        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='register.js') }}"></script>
{% endblock %}